export enum ErrorCodes {
  VOTE_LIMIT_EXCEEDED = "VOTE_LIMIT_EXCEEDED",
  ALREADY_VOTED_FOR_THIS_IDEA = "ALREADY_VOTED_FOR_THIS_IDEA",
  VOTE_SUCCESS = "VOTE_SUCCESS",
  IDEA_NOT_FOUND = "IDEA_NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
